/*
 * This source file was generated by the Gradle 'init' task
 */
package org.example

fun main() {
    val miFraccion = Fraccion(1,2)
    miFraccion.mostrar()

    val miFraccion2 = Fraccion(1,3)

    println(miFraccion.plus(miFraccion2))

}
